import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";
import { Section } from "~/components/ui/section";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Karteikarten</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pt-20">
        <Section className="space-y-4">
          <h1 className="mb-8 text-4xl font-semibold">Home</h1>

          <p>Nothing here yet. Start learning with your modules</p>
          <Button asChild variant="primary">
            <Link href="/modules">Modules</Link>
          </Button>
        </Section>
      </div>
    </>
  );
};

export default Home;
